#!/usr/bin/bash

PANEL_FIFO="/tmp/panel-fifo"
[[ -p $PANEL_FIFO ]] || mkfifo -m 600 "$PANEL_FIFO" 

. ~/.config/athanasius/athanasius.conf


FG_PANEL="#f4f4f4" 						# Panel's text colour
BG_PANEL="#80242466"						# Panel's background colour

focus="#fb9214"
focus_bg="#80242466"

unfocus="#b5a6b1"
unfocus_bg="#80242466"

urgent="#ff3333"

occupied="#fbaf55"
occupied_bg="#80242466"
ds=("" "" "" "" "" "" "")


FONT="Ubuntu:size=14"

# [ICONS]

# Icon font
ICONS="shmalebcollection:size=14"

# Volume
VOL1=""
VOL2=""
VOL3=""
VOLMUTE=""

# Battery
BATLOW=""
BAT1=""
BAT2=""
BAT3=""
BAT4=""
BATCHARGE=""

# Ram
RAM=""

# CPU
CPU=""

# Wifi
WIFI1=""
WIFI2=""
WIFI3=""
WIFIOFF=""

# Intervals, how often to fetch info for bar
RAM_INT="10"
CPU_INT="2"		# CPU interval must be non-zero for the function to work
WIFI_INT="10"
BAT_INT="50"


### Geometry
readonly PANEL_WIDTH=1920
readonly PANEL_HEIGHT=40
readonly PANEL_X=0		#panel offset to the right
readonly PANEL_Y=0			#panel offset down
GEOMETRY="$PANEL_WIDTH"x"$PANEL_HEIGHT"+"$PANEL_X"+"$PANEL_Y"

#MMWM workspaces
Workspaces() {
while read -t 60 -r wmout || true; do
    if [[ $wmout =~ ^(([[:digit:]]+:)+[[:digit:]]+ ?)+$ ]]; then
        read -ra desktops <<< "$wmout" && unset r
        for desktop in "${desktops[@]}"; do
            IFS=':' read -r d w m c u <<< "$desktop"
            fg="%{F$unfocus B$unfocus_bg}"
            ((w)) && fg="%{F$occupied B$occupied_bg}"
            ((c)) && fg="%{F$focus B$focus_bg}" 
      #      || fg="%{F$unfocus B$unfocus_bg}"
            ((u)) && w+="%{F$urgent}"
             #r+="[${w/tt/-}] $fg${ds[$d]} "
             r+="$fg ${ds[$d]} "
        done
        #r="${r%::*}"
    fi
    echo "W $r" 
done > "$PANEL_FIFO" &
}
tail -f /tmp/mmwm-file | Workspaces &


# Clock and date
#clock -sf 'S | %a %b %e | %I:%M | ' > "$PANEL_FIFO" &
Date(){
while true; do
	date "+S    %a %b %d   |   %I:%M %p   "
	sleep 30
done
}

Date > "$PANEL_FIFO" &

#CPU
Cpu(){
	while true ; do
	 awk '{u=$2+$4; t=$2+$4+$5; if (NR==1){u1=u; t1=t;} else print ($2+$4-u1) * 100 / (t-t1); }' <(grep 'cpu ' /proc/stat) <(sleep "$CPU_INT" ;grep 'cpu ' /proc/stat) | awk '{print "P '$CPU' " int($1+0.5) "%"}'
	done
}
Cpu > "$PANEL_FIFO" &



# Sound
# This function is not looped. This functions evaluates the correct alsa volume on first
# run. This function is mirrored in a separate script. The separate script echoes the
# same information to the panel fifo when volume is changed via volume keys in sxhkd.

Sound(){
	VOL=$(AWMgetvolume)
	if AWMgetmute;
		then
			if [ "$VOL" -gt 74 ]; then
					echo "V $VOL3"
				elif [ "$VOL" -gt 49 ]; then
				  echo "V $VOL2"
				else
					echo "V $VOL1"
			fi
	else
		echo "V $VOLMUTE"
	fi
}
Sound > "$PANEL_FIFO" &

#Wifi
Wifi(){
while true ; do
	WIFISTR=$( iwconfig $INTERFACE | awk -F' ' 'NR == 6 {gsub("Quality=",""); print "scale=3; " $2 "*100"}' | bc | cut -c 1-2 )
	ESSID=$(iwconfig $INTERFACE | awk -F' ' 'NR == 1 {gsub("ESSID:\"","");gsub("\"",""); print substr($4,1,4)}')
	if [ "$ESSID" = "ESSI" ]
		then
			echo "A $WIFIOFF"
			if [ "$WNOT" = "FALSE" ] ; then
				notify-send "Warning: Wifi Disconnected" && WNOT="TRUE"
			fi
	elif [ "$WIFISTR" -gt 66 ] ; then
			echo "A $WIFI3 " && WNOT="FALSE"
	elif [ "$WIFISTR" -gt 33 ] ; then
			echo "A $WIFI2 " && WNOT="FALSE"
	else
			echo "A $WIFI1 " && WNOT="FALSE"
	fi
	sleep "$WIFI_INT"
done
}
Wifi > "$PANEL_FIFO" &

#Battery
Battery() {
while true ; do
	CHARGING=$(cat /sys/class/power_supply/"$BATTERY"/status)
	BATPERC=$(cat /sys/class/power_supply/"$BATTERY"/capacity)
	if [ "$CHARGING" = "Discharging" ] ; then
				if [ "$BATPERC" -gt 95 ] ; then
					echo "D $BAT4 $BATPERC%"
				elif [ "$BATPERC" -gt 80 ] ; then
					echo "D $BAT3 $BATPERC%"
				elif [ "$BATPERC" -gt 50 ] ; then
					echo "D $BAT2 $BATPERC%"
				elif [ "$BATPERC" -gt 20 ] ; then
					echo "D $BAT1 $BATPERC%"
				else
					echo "D $BATLOW $BATPERC%"
				fi
			else
		echo "D $BATCHARGE $BATPERC% " 
	fi
sleep "$BAT_INT"
done
}
Battery > "$PANEL_FIFO" &

# Ram Usage, this is the low estimate, caches and buffers are not counted
Ram() {
while true ; do
	free -m | awk -F' ' 'NR==2 {print "R '$RAM' " $3 " MB "}'
sleep "$RAM_INT"
done
}
Ram > "$PANEL_FIFO" &


# Parse
bar() {
while read -r line ; do
	case $line in
		S*)
			# clock output
			sys="${line#?} %{B-}%{F-}"
			;;
		D*)
			# Battery
			bat="${line#?}"
			;;				
		V*)
			# Volume
			vol="${line#?}"
			;;					
		A*)
			# Wifi
			wifi="${line#?} %{B-}"
			;;	
		R*)
			#RAM
			ram="${line#?}"
			;;
		P*)
			#CPU
			cpu="${line#?}"
			;;
		W*)
			# mmwm's state
			wm="${line#?}   %{B-}%{F-}%{U-}"
			;;
	esac
	printf "%s\n" "%{l}${wm} %{c}%{B#80242466}${sys} %{r}%{B#80242466} ${ram} ${cpu} ${bat} ${vol} ${wifi}"
done
}



# The following function parses the output of `acpi_listen` to update the volume/battery
# when volume buttons are pressed or battery is plugged in (on laptop)

Acpiparse() {
while read -r line ; do
	case $line in
		ac_adapter*)
			case $line in
			*00000000) echo "bat disconnected"
				BATPERC=$(cat /sys/class/power_supply/"$BATTERY"/capacity)
				if [ "$BATPERC" -gt 95 ] ; then
					echo "D $BAT4 $BATPERC%"
				elif [ "$BATPERC" -gt 80 ] ; then
					echo "D $BAT3 $BATPERC%"
				elif [ "$BATPERC" -gt 50 ] ; then
					echo "D $BAT2 $BATPERC%"
				elif [ "$BATPERC" -gt 20 ] ; then
					echo "D $BAT1 $BATPERC%"
				else
					echo "D $BATLOW $BATPERC%"
				fi > "$PANEL_FIFO"
			;;
			*00000001) echo "bat connected"
			BATPERC=$(cat /sys/class/power_supply/"$BATTERY"/capacity)
			echo "D $BATCHARGE $BATPERC% "
			;;
			esac > "$PANEL_FIFO"
			;;
		button/mute*)
			VOL=$(AWMgetvolume)
			if AWMgetmute; then
				if [ "$VOL" -gt 74 ]; then
					echo "V $VOL3"
				elif [ "$VOL" -gt 49 ]; then
				  echo "V $VOL2"
				else
					echo "V $VOL1"
				fi
			else
				echo "V $VOLMUTE"
			fi > "$PANEL_FIFO"
			;;
		button/volume*)
		VOL=$(AWMgetvolume)
			if AWMgetmute; then
				if [ "$VOL" -gt 74 ]; then
					echo "V $VOL3"
				elif [ "$VOL" -gt 49 ]; then
				  echo "V $VOL2"
				else
					echo "V $VOL1"
				fi
			else
			echo "V $VOLMUTE"
			fi > "$PANEL_FIFO"
				;;
		esac
done
}

Acpiparse < <(acpi_listen) &

bar < "$PANEL_FIFO" \
	| lemonbar -p -a 32 -u 2 -n "$PANEL_WM_NAME" \
		-B "$BG_PANEL" \
		-F "$FG_PANEL" \
		-f "$FONT" -f "$ICONS" \
		-g "$GEOMETRY" \
