#!/usr/bin/bash

PANEL_FIFO="/tmp/panel-fifo"
[[ -p $PANEL_FIFO ]] || mkfifo -m 600 "$PANEL_FIFO" 
. $AWMdir/athanasius.conf

ds=("1" "2" "3" "4" "5" "6" "7")

#colours
focus="#00ffff"
focus_bg="#4c4c4c"

unfocus="#b5a6b1"
unfocus_bg="#262626"

urgent="#ff3333"

occupied="#00ffff"
occupied_bg="#262626"

FG_PANEL="#f4f4f5" 						# Panel's text colour
BG_PANEL="#262626"						# Panel's background colour

FONT="Terminus:size=11"



### Geometry
readonly PANEL_WIDTH=1920
readonly PANEL_HEIGHT=25
readonly PANEL_X=0		#panel offset to the right
readonly PANEL_Y=0			#panel offset down
GEOMETRY="$PANEL_WIDTH"x"$PANEL_HEIGHT"+"$PANEL_X"+"$PANEL_Y"

#MMWM workspaces
Workspaces() {
while read -t 60 -r wmout || true; do
    if [[ $wmout =~ ^(([[:digit:]]+:)+[[:digit:]]+ ?)+$ ]]; then
        read -ra desktops <<< "$wmout" && unset r
        for desktop in "${desktops[@]}"; do
            IFS=':' read -r d w m c u <<< "$desktop"
            fg="%{F$unfocus B$unfocus_bg}"
            ((w)) && fg="%{F$occupied B$occupied_bg}"
            ((c)) && fg="%{F$focus B$focus_bg}" 
      #      || fg="%{F$unfocus B$unfocus_bg}"
            ((u)) && w+="%{F$urgent}"
             #r+="[${w/tt/-}] $fg${ds[$d]} "
             r+="$fg ${ds[$d]} "
        done
        #r="${r%::*}"
    fi
    echo "W $r" 
done > "$PANEL_FIFO" &
}
tail -f /tmp/mmwm-file | Workspaces &

Date(){
while true; do
	date "+S %a %b %d | %I:%M %p "
	sleep 30
done
}

Date > "$PANEL_FIFO" &

# Parse
bar() {
while read -r line ; do
	case $line in
		S*)
			# clock output
			sys="${line#?} %{B-}%{F-}"
			;;
		W*)
			# mmwm's state
			wm="${line#?} %{B-}%{F-}"
			;;
	esac
	printf "%s\n" "%{l}${wm} %{c}${sys} "
done
}

bar < "$PANEL_FIFO" \
	| lemonbar -p -a 32 -u 2 \
		-B "$BG_PANEL" \
		-F "$FG_PANEL" \
		-f "$FONT" \
		-g "$GEOMETRY" \
