#!/usr/bin/bash

PANEL_FIFO="/tmp/panel-fifo"
[[ -p $PANEL_FIFO ]] || mkfifo -m 600 "$PANEL_FIFO" 

. $AWMdir/athanasius.conf

ds=("•" "•" "•" "•" "•" "•" "•")

#colours
focus="#262626"
focus_bg="#47cdda"

unfocus="#ebf0f2"
unfocus_bg="#2e2c2e"

urgent="#ff3333"

occupied="#ebf0f2"
occupied_bg="#424142"

FG_PANEL="#ebf0f2" 						# Panel's text colour
BG_PANEL="#2e2c2e"						# Panel's background colour

FONT="Terminus:size=11"



### Geometry
readonly PANEL_WIDTH=1920
readonly PANEL_HEIGHT=35
readonly PANEL_X=0		#panel offset to the right
readonly PANEL_Y=0			#panel offset down
GEOMETRY="$PANEL_WIDTH"x"$PANEL_HEIGHT"+"$PANEL_X"+"$PANEL_Y"

#MMWM workspaces
Workspaces() {
while read -t 60 -r wmout || true; do
    if [[ $wmout =~ ^(([[:digit:]]+:)+[[:digit:]]+ ?)+$ ]]; then
        read -ra desktops <<< "$wmout" && unset r
        for desktop in "${desktops[@]}"; do
            IFS=':' read -r d w m c u <<< "$desktop"
            fg="%{F$unfocus B$unfocus_bg}"
            ((w)) && fg="%{F$occupied B$occupied_bg}"
            ((c)) && fg="%{F$focus B$focus_bg}" 
      #      || fg="%{F$unfocus B$unfocus_bg}"
            ((u)) && w+="%{F$urgent}"
             #r+="[${w/tt/-}] $fg${ds[$d]} "
             r+="$fg ${ds[$d]} "
        done
        #r="${r%::*}"
    fi
    echo "W$r" 
done > "$PANEL_FIFO" &
}

Workspaces_bspwm() {
	bspc subscribe report | while read -r line ; do
			# bspwm's state
			wm=
			IFS=':'
			set -- ${line#?}
			while [ $# -gt 0 ] ; do
				item=$1
				name=${item#?}
				case $item in
					[mM]*)
						case $item in
							m*)
								# monitor
								FG=$focus
								BG=$focus_bg
								on_focused_monitor=
								;;
							M*)
								# focused monitor
								FG=$unfocus
								BG=$unfocus_bg
								on_focused_monitor=1
								;;
						esac
						# The following marks monitors for multi-monitor setup
						#[ $num_mon -lt 2 ] && shift && continue
						#wm="${wm}%{F${FG}}%{B${BG}}%{A:bspc monitor -f ${name}:} ${name} %{A}%{B-}%{F-}"
						;;
					[fFoOuU]*)
					# commented-out lines from here to line 230 are for multi-monitor setup.
					# the if-tests are needless for a single-monitor configuration.
						case $item in
							f*)
								# free desktop
								FG=$unfocus
								BG=$unfocus_bg
								;;
							F*)
					#			if [ "$on_focused_monitor" ] ; then
									# focused free desktop
									FG=$focus
									BG=$focus_bg
					#			else
					#				# active free desktop
					#				FG=$COLOR_FREE_FG
					#				BG=$COLOR_FREE_BG
					#				UL=$COLOR_FOCUSED_FREE_BG
					#			fi
								;;
							o*)
								# occupied desktop
								FG=$occupied
								BG=$occupied_bg
								;;
							O*)
					#			if [ "$on_focused_monitor" ] ; then
									# focused occupied desktop
									FG=$focus
									BG=$focus_bg
					#			else
					#				# active occupied desktop
					#				FG=$COLOR_OCCUPIED_FG
					#				BG=$COLOR_OCCUPIED_BG
					#				UL=$COLOR_FOCUSED_OCCUPIED_BG
					#			fi
								;;
							u*)
								# urgent desktop
								FG=$unfocus
								BG=$urgent
								;;
							U*)
					#			if [ "$on_focused_monitor" ] ; then
									# focused urgent desktop
									FG=$focus
									BG=$urgent
					#			else
					#				# active urgent desktop
					#				FG=$COLOR_URGENT_FG
					#				BG=$COLOR_URGENT_BG
					#				UL=$COLOR_FOCUSED_URGENT_BG
					#			fi
								;;
						esac
						wm="${wm}%{F${FG}}%{B${BG}}%{A:bspc desktop -f ${name}:} ${name} %{A}%{B-}%{F-}%{-u}"
						;;
				esac
				shift
			done
	echo "W$wm"
done
}

case "$WM" in
	bspwm)
    Workspaces_bspwm > "$PANEL_FIFO" &
    ;;
    mmwm)
    tail -f /tmp/mmwm-file | Workspaces &
    ;;
esac
    


Date(){
while true; do
	date "+S %a %b %d | %I:%M %p "
	sleep 30
done
}

Wifi(){
while true; do
	WIFISTR=$( iwconfig $INTERFACE | awk -F' ' 'NR == 6 {gsub("Quality=",""); print "scale=3; " $2 "*100"}' | bc | cut -c 1-2 )
	if [ -n "$WIFISTR" ] ; then
	 echo "N$WIFISTR%"
	else
		echo "NNONE"
	fi
	sleep 5
done
}

Bat(){
while true; do
	CHARGING=$(cat /sys/class/power_supply/"$BATTERY"/status)
	BATPERC=$(cat /sys/class/power_supply/"$BATTERY"/capacity)
	if [ "$CHARGING" = "Discharging" ] ; then
		echo "D$BATPERC%"
			else
		echo "D[$BATPERC%]" 
	fi
sleep 50
done
}

Sound(){
	VOL=$(AWMgetvolume)
	if AWMgetmute;
		then
		echo "V$VOL%"
	else
		echo "V[$VOL]"
	fi
}

Ram() {
while true ; do
	free -m | awk -F' ' 'NR==2 {print "R" $3 "MB"}'
sleep 3
done
}

Cpu(){
	while true ; do
	 awk '{u=$2+$4; t=$2+$4+$5; if (NR==1){u1=u; t1=t;} else print ($2+$4-u1) * 100 / (t-t1); }' <(grep 'cpu ' /proc/stat) <(sleep 2 ;grep 'cpu ' /proc/stat) | awk '{print "P" int($1+0.5) "%"}'
	done
}


Cpu > "$PANEL_FIFO" &
Ram > "$PANEL_FIFO" &
Date > "$PANEL_FIFO" &
Wifi > "$PANEL_FIFO" &
Bat > "$PANEL_FIFO" &
Sound > "$PANEL_FIFO" &

# Parse
bar() {
while read -r line ; do
	case $line in
		S*)
			# clock output
			sys="${line#?}%{B-}%{F-}"
			;;
		N*)
			# wifi
			net="${line#?}"
			;;
		D*)
			# battery
			bat="${line#?}"
			;;
		V*)
			# volume
			vol="${line#?}"
			;;
		R*)
			# memory
			ram="${line#?}"
			;;
		P*)
			# cpu
			cpu="${line#?}"
			;;
		W*)
			# workspaces
			wm="${line#?}%{B-}%{F-}"
			;;
	esac
	printf "%s\n" "%{l}${wm} %{c}${sys} %{r}%{B#47cdda F#262626} ${ram} \\ ${cpu} \\ ${vol} \\ ${bat} \\ ${net} %{B-F-}"
done
}

Acpiparse() {
while read -r line ; do
	case $line in
		ac_adapter*)
			case $line in
			*00000000)
			BATPERC=$(cat /sys/class/power_supply/"$BATTERY"/capacity)
				echo "D$BATPERC%"
			;;
			*00000001)
			BATPERC=$(cat /sys/class/power_supply/"$BATTERY"/capacity)
				echo "D[$BATPERC%]"
			;;
			esac > "$PANEL_FIFO"
			;;
		button/mute*)
			VOL=$(AWMgetvolume)
			if AWMgetmute; then
				echo "V$VOL%"
			else
				echo "V[$VOL]"
			fi
			;;
		button/volumeup*)
		VOL=$(AWMgetvolume)
			if AWMgetmute; then
				echo "V$VOL%"
			else
				echo "V[$VOL]"
			fi
				;;
		button/volumedown*)
		VOL=$(AWMgetvolume)
			if AWMgetmute; then
				echo "V$VOL%"
			else
				echo "V[$VOL]"
			fi
				;;
		esac > "$PANEL_FIFO"
done
}

Acpiparse < <(acpi_listen) &




bar < "$PANEL_FIFO" \
	| lemonbar -p -a 32 -u 2 \
		-B "$BG_PANEL" \
		-F "$FG_PANEL" \
		-f "$FONT" -f "Hack:size=11" \
		-g "$GEOMETRY" \
